import json

# without_replays = ['klzknvr', 'aehbtjb', 'tjmuwaf', 'snviznd', 'dueoanv', 'vfyaetn', 'skgepma', 'awxavjl', 'dfmvlxx', 'mtgvryq', 'ybntary', 'tuuaaah', 'xgozlvq', 'gxzplew', 'fmqybyq', 'smftdfx', 'ytwmbjv', 'krgwdag', 'vcmxmfw', 'gtxvkdp', 'evdkqkf', 'rpksgjk', 'wlaqzsw', 'zzuxjfr', 'ivugvzj', 'oljwbcq', 'sbayuxk', 'kzeheid', 'xndmpow', 'mbdmdja', 'mzozdcl', 'hwqmynz', 'cofxakc', 'cpmehow', 'lluitwu', 'akfvzvo', 'sxoeeps', 'fynrtgc', 'cxpzgpj', 'hpybukc', 'sqlpovy', 'ujkymih', 'ietmpvi', 'ozfnsvs', 'nrbpnhg', 'arzgpff', 'lzyaiga', 'xaobfvv', 'qyicxuv', 'ljkkwsh', 'vtrtacy', 'oiiwawv', 'ybmpnpy', 'bmghmkc', 'oamhjxi', 'shupxrw', 'wxkywnn', 'rkmzfum', 'cuyzpid', 'kwqnncc', 'angvmho', 'tifoyjj', 'ouulrhj', 'jpbfxcd', 'gwttfmm', 'gevuuiw', 'mqqgrfy', 'rxgzhkf', 'bdfglfk', 'ljkzgjk', 'iuealcb', 'cptbbef', 'ghkjxzn', 'gcjyxnp', 'bwwslvw', 'vrelolg', 'qfaggiz', 'gukziwq', 'xlpwgiy', 'lpweiml', 'gvmhita', 'vvaxfkh', 'werbbvg', 'sbvtquk', 'yhmkdqi', 'omjggnx', 'kjcptgq', 'lnyeopw', 'adoycdu', 'dqxehoa', 'jbygwlp', 'xwkqupk', 'qyuioif', 'bussugu', 'hxibmgd', 'frdcyrp', 'sotgsfl', 'cltkpvm', 'degahil', 'yfcwurq', 'wzqkdds', 'abrtuyx', 'evdfzmt', 'crwnlwr', 'yduqvyj', 'faqznos', 'hmtcgqe', 'pptieji', 'oxkcmdf', 'oucsxdt', 'xmjfzvn', 'touajtw', 'keeacvk', 'kibvedw', 'avryiio', 'fkbwzoj', 'klatidn', 'ybgfdzu', 'rhirlgx', 'jtwofwp', 'jytngue', 'ozmnhfn', 'fcnbybu', 'zrhrgyc', 'kzybkti', 'kckmjlj', 'noqntrw', 'zylfoni', 'rbhxzcn', 'dezslkz', 'zdmojda', 'iurdvbz', 'ipvmwoi', 'askysgp', 'jklfwtd', 'hjozcjl', 'vrfasyv', 'rqdnbho', 'ilfwuub', 'lzdmvnd', 'zxkjygw', 'dmeyeep', 'nqtusmq', 'yiuojzn', 'jvuxenv', 'fncmwgl', 'xubfncq', 'sihiccg', 'ubqjpve', 'mfjsubv', 'psfovtk', 'xemhqec', 'wutcywm', 'naookqt', 'gapvtib', 'mjozecm', 'wbillix', 'mexiern', 'ulkzxej', 'icmsxpa', 'gecsxud', 'dxqvyhy', 'tswxorl', 'sranukz', 'qcaaawy', 'xwaxixb', 'pzeluzp', 'chbbako', 'gwbmwzm', 'osviwzl', 'wlglvuu', 'atnmsix', 'rgewbcq', 'ixfmhlm', 'xtmddfb', 'hqryomv', 'bcadueh', 'ehmxkzi', 'fhbxwbi', 'qxbvgwx', 'lygqkdk', 'mpgqnes', 'zdnetmz', 'czceepb', 'bkxjeix', 'dsnofge', 'quyergz', 'cjbrzec', 'uboyhib', 'grjnfuk', 'aufgzvw', 'jcfnnoc', 'qbcqiib', 'mrkyqzt', 'xfcapyl', 'ukqpmno', 'rfrxpqd', 'bhvsozw', 'kjyozhh', 'pzzxnrr', 'uhnkyfq', 'sjtpgmo', 'lhsebrx', 'hwymovp', 'khbllcj', 'izvcamn', 'qzwabho', 'znksnit', 'rydjntn', 'bxnoafu', 'sjeiyhp', 'vfysmkl', 'gtrhwwb', 'uspntbv', 'vlplpes', 'pbrploe', 'xhckqhw', 'ykcanzt', 'dxdniko', 'ygiqsqg', 'iubrmxp', 'iwxrbsm', 'cezezgd', 'ocwgqha', 'zwwfmhy', 'cruzotd', 'plvhjif', 'akalybb', 'mqvrnzs', 'xmvfogb', 'rtgrakp', 'cgapzhx', 'kuwhpqu', 'iwophdp', 'tlsbull', 'xrqvpmz', 'antpgdo', 'cfxrujq', 'zspzvsj', 'kqtdllc', 'vhwwgaq', 'yjqybun', 'tpmjvjt', 'bxohzug', 'wfuhmzq', 'ghxspcb', 'phdlhwc', 'jyzgcgu', 'apfyesq', 'eodjxpy', 'brhgqkq', 'etzkmrj', 'wbsesgi']
# during download: without_replays = ['jyzgcgu', 'rbhxzcn', 'rhirlgx', 'smftdfx', 'plvhjif', 'arzgpff', 'lygqkdk', 'khbllcj', 'sihiccg', 'ybntary', 'rxgzhkf', 'mrkyqzt', 'werbbvg', 'ouulrhj', 'uspntbv', 'xtmddfb', 'bussugu', 'czceepb', 'mtgvryq', 'ubqjpve', 'sjtpgmo', 'qxbvgwx', 'phdlhwc', 'zspzvsj', 'vrfasyv', 'zzuxjfr', 'keeacvk', 'ykcanzt', 'aufgzvw', 'oiiwawv', 'wbsesgi', 'naookqt', 'pbrploe', 'sjeiyhp', 'dxdniko', 'vvaxfkh', 'zylfoni', 'ygiqsqg', 'tswxorl', 'kjyozhh', 'xlpwgiy', 'kjcptgq', 'bwwslvw', 'wxkywnn', 'sqlpovy', 'kckmjlj', 'wzqkdds', 'wutcywm', 'xndmpow', 'nrbpnhg', 'oucsxdt', 'quyergz', 'mbdmdja', 'gevuuiw', 'vfysmkl', 'ixfmhlm', 'sotgsfl', 'adoycdu', 'wbillix', 'sxoeeps', 'xwaxixb', 'akalybb', 'aaabtsd', 'lzyaiga', 'atnmsix', 'pzzxnrr', 'yhmkdqi', 'dmeyeep', 'ulkzxej', 'tifoyjj', 'pzeluzp', 'krgwdag', 'xemhqec', 'zdmojda', 'klatidn', 'cpmehow', 'osviwzl', 'lpweiml', 'mfjsubv', 'xwkqupk', 'xmvfogb', 'qyicxuv', 'wfuhmzq', 'tpmjvjt', 'xaobfvv', 'qzwabho', 'eodjxpy', 'vhwwgaq', 'mzozdcl', 'antpgdo', 'fncmwgl', 'cptbbef', 'kzybkti', 'zdnetmz', 'cezezgd', 'xrqvpmz', 'mjozecm', 'zwwfmhy', 'cfxrujq', 'rkmzfum', 'xhckqhw', 'jytngue', 'rgewbcq', 'hwqmynz', 'mqvrnzs', 'lnyeopw', 'zxkjygw', 'yiuojzn', 'zrhrgyc', 'rqdnbho', 'ozmnhfn', 'gvmhita', 'vlplpes', 'tuuaaah', 'lzdmvnd', 'kqtdllc', 'skgepma', 'mexiern', 'izvcamn', 'iubrmxp', 'rpksgjk', 'kuwhpqu', 'hmtcgqe', 'gtxvkdp', 'xubfncq', 'vcmxmfw', 'xmjfzvn', 'dxqvyhy', 'cgapzhx', 'ybmpnpy', 'ukqpmno', 'snviznd', 'chbbako', 'hqryomv', 'ipvmwoi', 'ujkymih', 'yjqybun', 'hpybukc', 'omjggnx', 'xfcapyl', 'touajtw', 'tlsbull', 'lhsebrx', 'qcaaawy', 'ljkkwsh', 'lluitwu', 'kwqnncc', 'qfaggiz', 'oxkcmdf', 'ocwgqha', 'kzeheid', 'mpgqnes', 'mqqgrfy', 'sranukz', 'ozfnsvs', 'yduqvyj', 'sbayuxk', 'oljwbcq', 'pptieji', 'rfrxpqd', 'jcfnnoc', 'cltkpvm', 'grjnfuk', 'vrelolg', 'shupxrw', 'uhnkyfq', 'vfyaetn', 'wlglvuu', 'xgozlvq', 'noqntrw', 'gukziwq', 'ietmpvi', 'znksnit', 'ytwmbjv', 'uboyhib', 'awxavjl', 'cruzotd', 'kibvedw', 'qyuioif', 'oamhjxi', 'ilfwuub', 'jtwofwp', 'dfmvlxx', 'wlaqzsw', 'tjmuwaf', 'yfcwurq', 'sbvtquk', 'vtrtacy', 'rydjntn', 'qbcqiib', 'ybgfdzu', 'psfovtk', 'ljkzgjk', 'degahil', 'aehbtjb', 'nqtusmq', 'rtgrakp']
# after completing the dataset
without_replays = ['izvcamn', 'ulkzxej', 'cltkpvm', 'dmeyeep', 'naookqt', 'krgwdag', 'xndmpow', 'gvmhita', 'lluitwu', 'osviwzl', 'jtwofwp', 'degahil', 'ipvmwoi', 'gevuuiw', 'chbbako', 'bussugu', 'pzzxnrr', 'rydjntn', 'awxavjl', 'pbrploe', 'uhnkyfq', 'mqqgrfy', 'hmtcgqe', 'smftdfx', 'lzyaiga', 'lzdmvnd', 'vfysmkl', 'nqtusmq', 'fncmwgl', 'atnmsix', 'aufgzvw', 'cruzotd', 'xlpwgiy', 'qbcqiib', 'xhckqhw', 'akalybb', 'xaobfvv', 'yhmkdqi', 'ybmpnpy', 'dxqvyhy', 'czceepb', 'cpmehow', 'cfxrujq', 'qyicxuv', 'znksnit', 'bwwslvw', 'kuwhpqu', 'hwqmynz', 'lygqkdk', 'jytngue', 'xmvfogb', 'rxgzhkf', 'yduqvyj', 'ixfmhlm', 'ietmpvi', 'antpgdo', 'yjqybun', 'phdlhwc', 'cptbbef', 'iubrmxp', 'ouulrhj', 'kzeheid', 'gtxvkdp', 'wbillix', 'wlaqzsw', 'keeacvk', 'oljwbcq', 'mrkyqzt', 'vrfasyv', 'sqlpovy', 'pptieji', 'noqntrw', 'vhwwgaq', 'oamhjxi', 'xubfncq', 'zspzvsj', 'lpweiml', 'ozfnsvs', 'sotgsfl', 'sihiccg', 'zwwfmhy', 'quyergz', 'adoycdu', 'gukziwq', 'dxdniko', 'oxkcmdf', 'xemhqec', 'uspntbv', 'rtgrakp', 'hpybukc', 'hqryomv', 'cgapzhx', 'zxkjygw', 'vfyaetn', 'aehbtjb', 'xtmddfb', 'shupxrw', 'cezezgd', 'dfmvlxx', 'ubqjpve', 'lnyeopw', 'oucsxdt', 'jcfnnoc', 'vrelolg', 'arzgpff', 'grjnfuk', 'ilfwuub', 'eodjxpy']
with open("splits_original.json", "r") as demo_file:
    demos_all = json.load(demo_file)
    
required_demos = demos_all["test_vis"] + demos_all["test_geo"] + demos_all["test_cat"] + demos_all["test_web"] + demos_all["iid_all"] + demos_all["valid"] + demos_all["test_iid"]
#print("Total required demos are:", len(required_demos))

download_demo = []
for demo in without_replays:
    if demo in required_demos:
        download_demo.append(demo)
print(download_demo)
print("Total downloadable demos:", len(download_demo))